import{a as b,S as L,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const w="20276088-c806993f1529a751a1465ba64",v="https://pixabay.com/api/";async function h(r,t=1,a=15){try{return(await b.get(v,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a}})).data}catch(s){throw console.error("Error fetching images:",s),s}}const m=document.querySelector(".gallery");function g(r){const t=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:o,views:i,comments:p,downloads:y})=>`
      <div class="photo-card">
        <a href="${s}">
          <img src="${a}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${p}</p>
          <p><b>Downloads:</b> ${y}</p>
        </div>
      </div>
    `).join("");m.insertAdjacentHTML("beforeend",t),E.refresh()}function S(){m.innerHTML=""}const E=new L(".gallery a"),q=document.querySelector("#search-form"),d=document.querySelector(".load-more"),u=document.querySelector(".loader");let l="",c=1;const f=15;q.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements.searchQuery.value.trim(),!l){n.error({title:"Error",message:"Please enter a search query"});return}c=1,S(),d.classList.add("hidden");try{u.classList.remove("hidden");const t=await h(l,c,f);if(t.hits.length===0){n.warning({title:"No Results",message:"No images found"});return}g(t.hits),d.classList.toggle("hidden",t.totalHits<=f)}catch{n.error({title:"Error",message:"Something went wrong"})}finally{u.classList.add("hidden")}});d.addEventListener("click",async()=>{c+=1;try{u.classList.remove("hidden");const r=await h(l,c,f);g(r.hits),c*f>=r.totalHits&&(d.classList.add("hidden"),n.info({message:"We're sorry, but you've reached the end of search results."})),P()}catch{n.error({title:"Error",message:"Something went wrong"})}finally{u.classList.add("hidden")}});function P(){var t;const r=((t=document.querySelector(".gallery .photo-card"))==null?void 0:t.getBoundingClientRect().height)||0;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
